name: Hello JSON Workflow
on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Run custom action with string
      - name: Run custom action with string
        id: greet_string
        uses: ./.github/actions/hello-pooja
        with:
          who-to-greet: 'Mona the Octocat'

      # Step 3: Show string output
      - name: Show string output
        run: |
          echo "Greeting: ${{ steps.greet_string.outputs.greeting }}"

      # Step 4: Run custom action with JSON
      - name: Run custom action with JSON
        id: greet_json
        uses: ./.github/actions/hello-pooja
        with:
          who-to-greet: '{"name":"GitHub Student"}'

      # Step 5: Show JSON output
      - name: Show JSON output
        run: |
          echo "Greeting: ${{ steps.greet_json.outputs.greeting }}"

      # Step 6: Upload workflow artifact using updated v4
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: greetings-artifact
          path: |
            output/
          retention-days: 7
          include-hidden-files: true
