name: Multi-Event Workflow

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
  schedule:
    - cron: '*/2 * * * *'  
  workflow_dispatch:

jobs:
  run-multi-event-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show event name
        run: |
          echo "This was triggered by: ${{ github.event_name }}"

      - name: Run your logic
        run: |
          echo "Running job for event: ${{ github.event_name }}"